import {StyleSheet} from "react-native";
import Colors from "./Colors";

export default StyleSheet.create({
  TEXT_STYLE: {
    fontFamily: "ProximaNovaA",
    fontSize: 16,
    fontWeight: "600",
    fontStyle: "normal",
    letterSpacing: 0,
    color: Colors.WHITE,
  },
  TEXT_STYLE_2: {
    fontFamily: "ProximaNovaA",
    fontSize: 16,
    fontWeight: "600",
    fontStyle: "normal",
    lineHeight: 18,
    letterSpacing: 0,
    textAlign: "center",
    color: Colors.GREYISH_BROWN,
  },
  TEXT_STYLE_3: {
    fontFamily: "ProximaNovaA",
    fontSize: 18,
    fontWeight: "normal",
    fontStyle: "normal",
    lineHeight: 22,
    letterSpacing: 0,
    textAlign: "center",
    color: Colors.WHITE,
  },
  TEXT_STYLE_4: {
    fontFamily: "ProximaNovaA",
    fontSize: 13,
    fontWeight: "600",
    fontStyle: "normal",
    letterSpacing: 0,
    textAlign: "center",
    color: Colors.WHITE,
  },
  TEXT_STYLE_5: {
    fontFamily: "ProximaNovaA",
    fontSize: 20,
    fontWeight: "bold",
    fontStyle: "normal",
    lineHeight: 22,
    letterSpacing: 0,
    textAlign: "center",
    color: Colors.WHITE,
  },
  TEXT_STYLE_6: {
    fontFamily: "ProximaNovaA",
    fontSize: 18,
    fontWeight: "bold",
    fontStyle: "normal",
    lineHeight: 22,
    letterSpacing: 0,
    color: Colors.GREYISH_BROWN,
  },
  TEXT_STYLE_7: {
    fontFamily: "ProximaNovaA",
    fontSize: 18,
    fontWeight: "bold",
    fontStyle: "normal",
    letterSpacing: 0,
    color: Colors.GREYISH_BROWN,
  },
});
